server:
  port: 9006
spring:
  application:
    name: tensquare-spit #指定服务名
  data:
    mongodb:
      host: 192.168.179.128
      database: spitdb
  redis:
    host: 192.168.179.128
  rabbitmq:
    host: 192.168.179.128
jwt:
  config:
    key: eknaij
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:9761/eureka
  instance:
    prefer-ip-address: true
